kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-grafana-pvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: ceph-rbd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
