apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-single
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-single
  template:
    metadata:
      labels:
        app: mysql-single
    spec:
      containers:
      - name: mysql-single
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        #resources:
        #  limits:
        #    memory: "500Mi"
        #    cpu: "500m"
        #  requests:
        #    memory: "500Mi"
        #    cpu: "250m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234xpxp"
        volumeMounts:
        - name: mysql-single-volume
          mountPath: /var/lib/mysql
      volumes:
       - name: mysql-single-volume
         persistentVolumeClaim:
           claimName: ceph-mysql-pvc
