apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-rules
  annotations:
    kubernets.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - nginx.myweb.com
    - tomcat.myweb.com
    - dashboard.myweb.com
    secretName: tls-myweb
  rules:
  - host: nginx.myweb.com
    http:
      paths:
      - path:
        backend:
          serviceName: nginx-test
          servicePort: 80
  - host: tomcat.myweb.com
    http:
      paths:
      - path:
        backend:
          serviceName: java-demo
          servicePort: 80
  - host: dashboard.myweb.com
    http:
      paths:
      - path:
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
