apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-grafana-pvc
  namespace: kube-system
spec:
  storageClassName: nfs-grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
