apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-alertmanager-pv 
  labels:
    name: nfs-alertmanager-pv 
spec:
  capacity:
    storage: 2Gi 
  accessModes:
  - ReadWriteOnce 
  storageClassName: standard
  nfs: 
    path: /pub/mnt/alertmanager
    server: 192.168.19.135
  persistentVolumeReclaimPolicy: Retain
