---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-client
  labels:
    app: es
    role: client
spec:
  replicas: 3
  serviceName: es-client
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: es
      role: client
  template:
    metadata:
      labels:
        app: es
        role: client
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - es
#              - key: role
#                operator: In
#                values:
#                - client
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - es
#            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: "chown"
        image: elasticsearch:7.6.0
        imagePullPolicy: "IfNotPresent"
        command:
        - /bin/bash
        - -c
        - >
          set -e;
          set -x;
          chown -R elasticsearch:elasticsearch /usr/share/elasticsearch;
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      - name: init-sysctl
        image: elasticsearch:7.6.0
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-client
        image: elasticsearch:7.6.0
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        ports:
        - containerPort: 9200
          name: http 
        - containerPort: 9300
          name: transport
        env:
        - name:  "ES_JAVA_OPTS"
          value: "-Xms2g -Xmx2g"
        - name: "cluster.name"
          value: "es"
        - name: "node.name"
          value: "${HOSTNAME}"
        - name:  "bootstrap.memory_lock"
          value: "false"
        - name: "discovery.seed_hosts"
          value: "es-discovery"
        - name: "cluster.initial_master_nodes"
          value: "es-master-0,es-master-1,es-master-2"
        - name: "discovery.zen.ping_timeout"
          value: "5s"
        - name: "node.master"
          value: "false"
        - name: "node.data"
          value: "false"
        - name: "node.ingest"
          value: "true"
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 20
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: ceph-rbd
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
